# Required
version: 2

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats: all

# Set the version of Python and requirements
python:
  version: "3.10"
  install:
    - requirements: docs/requirements.txt
